### ISSUE TITLE
npmパッケージの更新

### ISSUE THREAD

**Issue by 59naga** [niwaringo/moji#5]
2017年9月4日現在発行されている`moji@0.5.1`は動作しません。

```bash
yarn add moji
# ├─ moji@0.5.1

nvm use 0
# Now using node v0.12.13 (npm v2.15.0)

node
require('moji')('test').convert('HEtoZE')
# TypeError: Cannot read property 'start' of undefined
#     at Moji._mojisyuType (/Users/59naga/Downloads/hoge/node_modules/moji/src/moji.core.js:184:16)
#     at Moji.convert (/Users/59naga/Downloads/hoge/node_modules/moji/src/moji.core.js:32:14)
#     at repl:1:25
#     at REPLServer.defaultEval (repl.js:132:27)
#     at bound (domain.js:291:14)
#     at REPLServer.runBound [as eval] (domain.js:304:12)
#     at REPLServer.<anonymous> (repl.js:279:12)
#     at REPLServer.emit (events.js:107:17)
#     at REPLServer.Interface._onLine (readline.js:214:10)
#     at REPLServer.Interface._line (readline.js:553:8)
```

現在のレポジトリ https://github.com/niwaringo/moji/commit/a1511d1776e460007a41d57d147739fc56dd7b49 を直接`npm install`する場合は動作します。

```bash
npm install https://github.com/niwaringo/moji
# moji@1.2.0 node_modules/moji

node
require('moji')('test').convert('HEtoZE')
# { _str: 'ｔｅｓｔ',
# ...
```

npmパッケージの更新をお願い致します。

**Comment by raviqqe** [comment]
Any update on this?

**Comment by ghost** [comment]
npmにv1.2.0のアップお願いします。
